### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by nagi1** [yoeunes/voteable#11]
Hey, I love the thought and work you putted in this. But I feel it's a shame that it not support neither of Laravel 7 or 8.

It's kinda easy to support these versions by editing composer.json.

BTW I'm welling to PR this if you're welcoming them.

**Comment by yoeunes** [comment]
hello @nagi1 thank's for your interrest, yeah you're right, honestly i just forget about some packages because i didn't used them for some times.
i'll try to update this one

**Comment by yoeunes** [comment]
can you please upgrade to v1.1 and tell me if it works for you ?

**Comment by nagi1** [comment]
I have tested this on laravel 8 and it works beautifully.

Thank you for fixing this :)
